### PR TITLE
Fix unicode error and be py3 ready

### PR DESCRIPTION
**Pull request by pypingou**

### CODE REVIEW

**Comment by ralphbean** [comment]
You can add ``from __future__ import print_function`` at the very top of the file to make this work on both py2 and py3, no?

**Comment by pypingou** [comment]
python 2.6 supports ``print()`` so I thought that was simple enough :]

**Comment by ralphbean** [comment]
Super duper.  :+1:

**Comment by pypingou** [comment]
Cool, thanks! :)

**Pull request merged**
