### PR TITLE
Support python3 and fix mailing list error

### PR DESCRIPTION
**Pull request by didier13150**
Hi pypingou,
This PR fix some problems:
- script is not running with python3 (still support python2 for now)
- Fix mailing lists (gname to lists.fedoraproject.org)
- Fix bugzilla search (due to new redhat bugzilla)
- Fix all_comments in _get_bugzilla_history function which is always false
- Add option to list all koji actions

I know that Makefile is added to this PR, but I don't want to waste time to remove it. Feel free to not accept this file.
Thank you for your interest about this PR.

Didier.

### CODE REVIEW

**Comment by sanjayankur31** [comment]
Works, tested it out. Thanks very much @didier13150

**Comment by pypingou** [comment]
Hm, I'm not sure what the makefile is for?

I think we should drop the dependency on fedora_cert and rather use https://pagure.io/cccolutils

**Comment by didier13150** [comment]
Currently, makefile is an easy way to have pypingou script working without
any problem (install deps automatically). It's not the way this script
should work.

**Comment by pypingou** [comment]
> makefile is an easy way to have pypingou script working without any problem (install deps automaticall

I'd rather we document things properly in the README if it's not already there.

**Comment by didier13150** [comment]
Sure, but currently, we discuss about a better solution in fedora-devel mailing list. Do you want I remove Makefile from PR ? I just not want to waste time to remove it from inital PR. But if you prefere ..., I remove it
And what do you think about changes in the main script file ?

**Comment by pypingou** [comment]
I would prefer we remove the Makefile.
The rest of the changes are looking alright at first glance. I'll likely need to spend a bit more time on them as there are many.

**Comment by didier13150** [comment]
Makefile was removed

**Comment by pypingou** [comment]
Alright, let's squash the commits, I'll give it a last testing and we'll merge if all works well :)

**Comment by pypingou** [comment]
ping?

**Comment by didier13150** [comment]
Squashed.

**Comment by pypingou** [comment]
Ok, it works but the mailing list seems to not work properly, I've tested it with my email and I get:
````
Last email on archived mailing list:
  - devel@lists.fedoraproject.org: 9 years, 8 months
````

Which I know isn't true :)

**Comment by didier13150** [comment]
Well, method to search messages is completely deprecated. 

1. Since fedora move mailing list, a lot of new mailing list was created (more than 500). So list cannot be maintain properly. 
2. Search in all lists: a little bit long and some extra occurrence can be found (with my fas: tartare, I can found occurrence about "steak tartare", don't laugh please)
I don't know how to deal with problems...

**Comment by pypingou** [comment]
But we're only searching some mailing list, in purpose not all of them. One of the list we're explicitely searching is the devel list which is returning invalid data (or could it be that we're returning my first post there as opposed to my latest one?)

I definitely agree that we don't want to search all of the lists :)

**Comment by didier13150** [comment]
Switch back to search email address instead of fas. Query answer is ordered by score (by default), I don't remember if that was the case when I was submitted my PR, but it was working for 3 different queries.
And to be clear, query answer report all subjects about discussion the user participate, and the date of the last message for each subject, even the author is not the one who we searching for.

**Comment by pypingou** [comment]
> Switch back to search email address instead of fas.

This confuses me, we are doing both and they both provide two different elements

**Comment by frenzymadness** [comment]
My two cents here:
* If you want to keep Python 2 compatibility, please use `six.moves` module for incompatible imports.
* Please drop dependency on `fedora_cert` module which is not available in Fedora 30.

**Comment by frenzymadness** [comment]
Also, if you need any help with porting, let me know!

**Comment by junaruga** [comment]
> Please drop dependency on fedora_cert module which is not available in Fedora 30.

Shall we modify like this? Then it works on Fedora 30 and python3 without `fedora_cert`?

```
$ git diff
diff --git a/fedora_active_user.py b/fedora_active_user.py
index 6c8abe9..f32ea38 100644
--- a/fedora_active_user.py
+++ b/fedora_active_user.py
@@ -22,7 +22,6 @@ project.
 """
 
 import datetime
-import fedora_cert
 import getpass
 import json
 import logging
@@ -295,6 +294,7 @@ def _get_last_website_login(username):
 
     log.debug('Querying FAS for user: {0}'.format(username))
     try:
+        import fedora_cert
         fasusername = fedora_cert.read_user_cert()
     except Exception:
         log.debug('Could not read Fedora cert, using login name')
```

**Comment by pypingou** [comment]
In https://github.com/pypingou/fedora-active-user/pull/15 we keep the mailing list support working by migrating it to hyperkitty :)

**Comment by pypingou** [comment]
PY3 support + a few fixes including the ones for bugzilla and koji can be found at: https://github.com/pypingou/fedora-active-user/pull/16

**Comment by pypingou** [comment]
@didier13150 if you are still interested in fixing these two issues:
> Fix all_comments in _get_bugzilla_history function which is always false
> Add option to list all koji actions

I'll happily review a PR for them :)
If this PR had not been one large commit, I've have cherry picked them but if you are still interested, I would prefer we fix these in a new PR, one commit per fix and give you the proper attribution.

**Comment by didier13150** [comment]
@pypingou Ok I will submit splitted PR ASAP

**Comment by pypingou** [comment]
@didier13150 do you want to update this PR or should we close it and review a new one?

**Comment by didier13150** [comment]
Please close this PR. I will submit PRs with more granularity.

**Comment by pypingou** [comment]
Let's close then :)

**Pull request closed without merging**
